### ISSUE TITLE
[24] reactでTodoアプリを作成する

### ISSUE THREAD

**Issue by sho-kasama** [sho-kasama/many__study#48]
## TODO 

- [x] <a href="https://qiita.com/mikan3rd/items/496a87fc8b76263d0a91">Reactの環境構築</a>
- [x] <a href="https://qiita.com/mikan3rd/items/20152cdd63a708264a9e">Todoアプリを作成する</a>
- [x] <a href="http://qs.nndo.jp/2017/03/25/392/">簡単なtodoリスと作成</a>
